package lsp

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"go.lsp.dev/protocol"
	"go.lsp.dev/uri"

	"github.com/remoteoss/dexter/internal/parser"
	"github.com/remoteoss/dexter/internal/store"
)

// ashFixture returns a server whose index holds the Ash fixture's resource, its
// domain, and the two Spark extension modules that supply their DSL macros.
// Those extension sources must be indexed for the extensions to resolve, which
// mirrors a real project: Dexter indexes deps/ as well as lib/.
func ashFixture(t *testing.T, files ...string) (*Server, string) {
	t.Helper()
	root := os.Getenv("DEXTER_ASH_FIXTURE")
	if root == "" {
		root = filepath.Join("testdata", "ash_generated_functions")
		for _, required := range []string{
			filepath.Join("_build", "dev", "lib", "ash", "ebin", "Elixir.Ash.Resource.Dsl.beam"),
			filepath.Join("_build", "dev", "lib", "ash", "ebin", "Elixir.Ash.Resource.Dsl.CodeInterface.Define.beam"),
		} {
			if _, err := os.Stat(filepath.Join(root, required)); err != nil {
				t.Skip("compile testdata/ash_generated_functions or set DEXTER_ASH_FIXTURE")
			}
		}
	}
	// The store keys rows by path and the LSP resolves URIs to absolute ones, so
	// the fixture root has to be absolute too or nothing matches.
	abs, err := filepath.Abs(root)
	if err != nil {
		t.Fatal(err)
	}

	s, err := store.Open(t.TempDir())
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = s.Close() })
	server := NewServer(s, abs)
	server.snippetSupport = true

	defaults := []string{
		"lib/dexter_ash_beam_fixture/accounts/user.ex",
		"lib/dexter_ash_beam_fixture/accounts.ex",
		"deps/ash/lib/ash/resource/dsl.ex",
		"deps/ash/lib/ash/domain/dsl.ex",
	}
	if len(files) > 0 {
		defaults = files
	}
	for _, rel := range defaults {
		path := filepath.Join(abs, rel)
		defs, refs, err := parser.ParseFile(path)
		if err != nil {
			t.Fatalf("parse %s: %v", rel, err)
		}
		if err := s.IndexFileWithRefs(path, defs, refs); err != nil {
			t.Fatal(err)
		}
	}
	return server, abs
}

// openFixtureFile puts a fixture file in the document store and returns its URI
// and lines.
func openFixtureFile(t *testing.T, server *Server, root, rel string) (string, []string) {
	t.Helper()
	path := filepath.Join(root, rel)
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	docURI := string(uri.File(path))
	server.docs.Set(docURI, string(raw))
	return docURI, strings.Split(string(raw), "\n")
}

// Ash's DSL macros are generated by Spark from %Spark.Dsl.Section{} data at
// compile time. There is no defmacro for them in any source file, they leave no
// trace in the consumer's export or import tables because macros expand away, and
// the use chain that injects them is itself generated code. The compiled module's
// `extensions` attribute is the only record of which module provides them.
func TestSparkDSLMacroCompletionAndHover(t *testing.T) {
	server, root := ashFixture(t,
		"lib/dexter_ash_beam_fixture/accounts.ex",
		"deps/ash/lib/ash/domain/dsl.ex",
	)
	domainURI, _ := openFixtureFile(t, server, root, "lib/dexter_ash_beam_fixture/accounts.ex")

	// The provider must be discovered from the compiled attributes, not guessed.
	providers := server.macroProvidersForModule("DexterAshBeamFixture.Accounts")
	if len(providers) != 1 || providers[0] != "Ash.Domain.Dsl" {
		t.Fatalf("expected [Ash.Domain.Dsl] from the extensions attribute, got %v", providers)
	}

	// accounts.ex has "  resources do" on its fourth line; sit past the name.
	items := completionAt(t, server, domainURI, 3, 11)
	if !hasCompletionItem(items, "resources") {
		t.Errorf("expected the generated resources macro, got %v", labelsOf(items))
	}
	// A DSL section macro's only argument is the do block, so completing it must
	// produce the block rather than `resources(body)`.
	if snippet := snippetFor(items, "resources"); snippet != "resources do\n\t$0\nend" {
		t.Errorf("resources snippet = %q, want a do block", snippet)
	}

	hover, err := server.Hover(context.Background(), &protocol.HoverParams{
		TextDocumentPositionParams: protocol.TextDocumentPositionParams{
			TextDocument: protocol.TextDocumentIdentifier{URI: protocol.DocumentURI(domainURI)},
			Position:     protocol.Position{Line: 3, Character: 4},
		},
	})
	if err != nil {
		t.Fatal(err)
	}
	if hover == nil {
		t.Fatal("expected a hover for the generated macro")
	}
	if !strings.Contains(hover.Contents.Value, "defmacro resources(body)") {
		t.Errorf("hover is missing the generated signature: %q", hover.Contents.Value)
	}
}

// Entity macros live one level deeper: `define` belongs to
// Ash.Resource.Dsl.CodeInterface.Define, which is inside `code_interface do`.
// Which macros are in scope therefore depends on the do block the cursor is in,
// and section macros must not leak into a section body.
func TestNestedDSLMacroScope(t *testing.T) {
	server, root := ashFixture(t)
	resourceURI, lines := openFixtureFile(t, server, root,
		"lib/dexter_ash_beam_fixture/accounts/user.ex")

	sectionLine, entityLine := -1, -1
	for i, line := range lines {
		switch {
		case strings.Contains(line, "code_interface do"):
			sectionLine = i
		case sectionLine >= 0 && entityLine < 0 && strings.Contains(line, "define"):
			entityLine = i
		}
	}
	if sectionLine < 0 || entityLine < 0 {
		t.Fatalf("fixture lacks a code_interface block: %v", lines)
	}

	// Inside the section body, the entity macro is offered.
	entityCol := uint32(strings.Index(lines[entityLine], "define") + len("define"))
	inside := completionAt(t, server, resourceURI, uint32(entityLine), entityCol)
	if !hasCompletionItem(inside, "define") {
		t.Errorf("expected define inside code_interface, got %v", labelsOf(inside))
	}
	if hasCompletionItem(inside, "code_interface") {
		t.Errorf("a section macro must not be offered inside its own body: %v", labelsOf(inside))
	}

	// On the section call itself the cursor is at module level, so the sections are
	// offered and the entity macro is not.
	sectionCol := uint32(strings.Index(lines[sectionLine], "code_interface") + len("code_interface"))
	outside := completionAt(t, server, resourceURI, uint32(sectionLine), sectionCol)
	if !hasCompletionItem(outside, "code_interface") {
		t.Errorf("expected code_interface at module level, got %v", labelsOf(outside))
	}
	if hasCompletionItem(outside, "define") {
		t.Errorf("define belongs to the section body, not module level: %v", labelsOf(outside))
	}
}

// The block path resolves through the innermost DSL block, and language forms
// fall away because they derive to modules that do not exist.
func TestDslScopeResolvesInnermostBlock(t *testing.T) {
	server, _ := ashFixture(t)
	extensions := []string{"Ash.Resource.Dsl"}

	tests := []struct {
		name      string
		blockPath []string
		want      []string
	}{
		{"module level", []string{"defmodule"}, nil},
		{
			"section body", []string{"defmodule", "code_interface"},
			[]string{
				"Ash.Resource.Dsl.CodeInterface.Define",
				"Ash.Resource.Dsl.CodeInterface.DefineCalculation",
				"Ash.Resource.Dsl.CodeInterface.Options",
			},
		},
		{
			"entity body", []string{"defmodule", "code_interface", "define"},
			[]string{
				"Ash.Resource.Dsl.CodeInterface.Define.CustomInput",
				"Ash.Resource.Dsl.CodeInterface.Define.Options",
			},
		},
		{
			// The attributes section has no Options module of its own, and each
			// entity's Options is two segments down, so it correctly belongs to the
			// `attribute do` body rather than here.
			"attributes section", []string{"defmodule", "attributes"},
			[]string{
				"Ash.Resource.Dsl.Attributes.Attribute",
				"Ash.Resource.Dsl.Attributes.CreateTimestamp",
				"Ash.Resource.Dsl.Attributes.IntegerPrimaryKey",
				"Ash.Resource.Dsl.Attributes.UpdateTimestamp",
				"Ash.Resource.Dsl.Attributes.UuidPrimaryKey",
				"Ash.Resource.Dsl.Attributes.UuidV7PrimaryKey",
			},
		},
		{
			"entity options one level down", []string{"defmodule", "attributes", "attribute"},
			[]string{"Ash.Resource.Dsl.Attributes.Attribute.Options"},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := server.dslScopeModules(extensions, tt.blockPath)
			names := make([]string, 0, len(got))
			for _, provider := range got {
				names = append(names, provider.module)
				if !strings.HasSuffix(provider.beamPath, "Elixir."+provider.module+".beam") {
					t.Errorf("provider %s has beam path %s", provider.module, provider.beamPath)
				}
			}
			if strings.Join(names, ",") != strings.Join(tt.want, ",") {
				t.Errorf("dslScopeModules(%v) = %v, want %v", tt.blockPath, names, tt.want)
			}
		})
	}
}

// Hovering a generated code-interface function must render the documentation
// prose recorded in the BEAM, which is what the doc offsets exist for.
func TestHoverGeneratedFunctionDocs(t *testing.T) {
	server, _ := ashFixture(t, "lib/dexter_ash_beam_fixture/accounts/user.ex")

	// Ash generates get_by_id/1..3 with documentation; the source has no such def.
	hover := server.hoverFromGenerated("DexterAshBeamFixture.Accounts.User", "", "get_by_id")
	if hover == nil {
		t.Fatal("expected a hover for the generated get_by_id")
	}
	value := hover.Contents.Value
	if hover.Contents.Kind != protocol.Markdown {
		t.Errorf("hover kind = %v, want markdown", hover.Contents.Kind)
	}
	// Every arity of one function is contiguous in the sorted slice, so a single
	// hover lists them all rather than picking one arbitrarily.
	for _, signature := range []string{
		"def get_by_id(id)",
		"def get_by_id(id, params)",
		"def get_by_id(id, params, opts)",
	} {
		if !strings.Contains(value, signature) {
			t.Errorf("hover is missing %q:\n%s", signature, value)
		}
	}
	// The prose comes from the doc span recorded during the Docs walk, so this is
	// what proves hover can read documentation completion deliberately skipped.
	if !strings.Contains(value, "Calls the read action on") {
		t.Errorf("hover is missing the documentation prose:\n%s", value)
	}

	if got := server.hoverFromGenerated("DexterAshBeamFixture.Accounts.User", "", "not_a_real_function"); got != nil {
		t.Errorf("expected no hover for an unknown function, got %q", got.Contents.Value)
	}
}

func labelsOf(items []protocol.CompletionItem) []string {
	labels := make([]string, 0, len(items))
	for _, item := range items {
		labels = append(labels, item.Label)
	}
	return labels
}

func snippetFor(items []protocol.CompletionItem, label string) string {
	for _, item := range items {
		if item.Label == label || item.FilterText == label {
			return item.InsertText
		}
	}
	return ""
}
