package mcp

import (
	"context"
	"fmt"
	"strings"

	"github.com/remoteoss/dexter/internal/lsp"
)

type DefinitionParams struct {
	Module   string `json:"module" jsonschema:"fully-qualified module name, e.g. MyApp.Accounts (aliases are not resolved)"`
	Function string `json:"function,omitempty" jsonschema:"function/macro/type name without arity; omit to look up the module itself"`
}

func (h *Handler) definition(ctx context.Context, args DefinitionParams) (string, error) {
	module := strings.TrimSpace(args.Module)
	if module == "" {
		return "", fmt.Errorf("module must not be empty")
	}
	function := strings.TrimSpace(args.Function)

	if function == "" {
		return h.moduleDefinition(module)
	}

	// The same name navigation as go-to-definition and `dexter lookup`: use
	// chains, generated functions, and the lines that declared them. Direct
	// definitions come first because they show whether this is a defdelegate
	// facade.
	direct, err := h.lsp.LookupName(module, function, lsp.NameLookupOptions{})
	if err != nil {
		return "", fmt.Errorf("looking up function: %w", err)
	}

	var b strings.Builder
	if len(direct) == 0 {
		// No direct definition. The function can still resolve through a
		// defdelegate chain.
		resolved, err := h.lsp.LookupName(module, function, lsp.NameLookupOptions{FollowDelegates: true})
		if err != nil {
			return "", fmt.Errorf("looking up function: %w", err)
		}
		if len(resolved) == 0 {
			return fmt.Sprintf("%s.%s is not in the index. It can be generated by a macro that the index cannot see, or misspelled. Try dexter_search or dexter_module_api %s.", module, function, module), nil
		}
		for i, r := range resolved {
			if i == maxDefinitionClauses {
				writeMoreClauses(&b, len(resolved)-i)
				break
			}
			h.writeDefinition(&b, module, function, r)
		}
		return b.String(), nil
	}

	for i, r := range direct {
		if i == maxDefinitionClauses {
			writeMoreClauses(&b, len(direct)-i)
			break
		}
		h.writeDefinition(&b, module, function, r)
		if r.Kind != "defdelegate" {
			continue
		}
		targetModule, targetFunction, ok := h.delegateTargetAt(module, function, r)
		if !ok {
			continue
		}
		targets, err := h.lsp.LookupName(module, function, lsp.NameLookupOptions{FollowDelegates: true})
		if err != nil || len(targets) == 0 {
			continue
		}
		fmt.Fprintf(&b, "\nDelegates to %s.%s:\n", targetModule, targetFunction)
		written := 0
		for j, t := range targets {
			if t.FilePath == r.FilePath && t.Line == r.Line {
				continue
			}
			if written == maxDefinitionClauses {
				writeMoreClauses(&b, len(targets)-j)
				break
			}
			h.writeDefinition(&b, targetModule, targetFunction, t)
			written++
		}
	}
	return b.String(), nil
}

// maxDefinitionClauses caps the clauses that one definition answer shows. A
// generated function can have thousands of clauses, and each one shown costs
// its docs and its head line.
const maxDefinitionClauses = 20

func writeMoreClauses(b *strings.Builder, n int) {
	fmt.Fprintf(b, "\n… and %d more clause(s) not shown.\n", n)
}

// delegateTargetAt names the function that the defdelegate at r forwards to.
func (h *Handler) delegateTargetAt(module, function string, r lsp.NameLocation) (targetModule, targetFunction string, ok bool) {
	defs, err := h.store.LookupFunction(module, function)
	if err != nil {
		return "", "", false
	}
	for _, d := range defs {
		if d.FilePath != r.FilePath || d.Line != r.Line || d.DelegateTo == "" {
			continue
		}
		targetFunction = function
		if d.DelegateAs != "" {
			targetFunction = d.DelegateAs
		}
		return d.DelegateTo, targetFunction, true
	}
	return "", "", false
}

func (h *Handler) moduleDefinition(module string) (string, error) {
	results, err := h.lsp.LookupName(module, "", lsp.NameLookupOptions{})
	if err != nil {
		return "", fmt.Errorf("looking up module: %w", err)
	}
	if len(results) == 0 {
		return fmt.Sprintf("Module %s is not in the index. Use dexter_search to find the right name, or dexter_reindex if it was just created.", module), nil
	}

	var b strings.Builder
	for _, r := range results {
		a, ok := h.at(r.FilePath, r.Line)
		if !ok {
			fmt.Fprintf(&b, "%s %s - %s:%d\n", moduleKindLabel(r.Kind), module, h.relPath(r.FilePath), r.Line)
			continue
		}
		fmt.Fprintf(&b, "%s %s - %s:%d%s\n", moduleKindLabel(r.Kind), module, h.relPath(r.FilePath), a.line, a.label())
		if r.Kind != "defimpl" {
			if doc := a.tokenized().ExtractModuledoc(a.line - 1); doc != "" {
				fmt.Fprintf(&b, "\n%s\n", strings.TrimRight(doc, "\n"))
			}
		}
	}
	return b.String(), nil
}

// writeDefinition renders one definition with location, @spec/@doc, and the
// definition head line.
func (h *Handler) writeDefinition(b *strings.Builder, module, function string, r lsp.NameLocation) {
	kind := r.Kind
	if kind == "" {
		kind = "def"
	}
	a, ok := h.at(r.FilePath, r.Line)
	if !ok {
		fmt.Fprintf(b, "%s (%s) - %s:%d\n", symbolName(module, function, r.Arity), kind, h.relPath(r.FilePath), r.Line)
		return
	}
	fmt.Fprintf(b, "%s (%s) - %s:%d%s\n", symbolName(module, function, r.Arity), kind, h.relPath(r.FilePath), a.line, a.label())
	doc, spec := a.tokenized().ExtractDocAbove(a.line - 1)
	if spec != "" {
		fmt.Fprintf(b, "%s\n", spec)
	}
	if head, ok := a.lineText(); ok {
		fmt.Fprintf(b, "%s\n", strings.TrimRight(head, " \t"))
	}
	if doc != "" {
		fmt.Fprintf(b, "\n%s\n", strings.TrimRight(doc, "\n"))
	}
}
