package mcp

import (
	"context"
	"fmt"
	"strings"

	"github.com/modelcontextprotocol/go-sdk/mcp"

	"github.com/remoteoss/dexter/internal/lsp"
	"github.com/remoteoss/dexter/internal/store"
)

type DefinitionParams struct {
	Module   string `json:"module" jsonschema:"fully-qualified module name, e.g. MyApp.Accounts (aliases are not resolved)"`
	Function string `json:"function,omitempty" jsonschema:"function/macro/type name without arity; omit to look up the module itself"`
}

func (h *Handler) definitionHandler(ctx context.Context, req *mcp.CallToolRequest, args DefinitionParams) (*mcp.CallToolResult, any, error) {
	module := strings.TrimSpace(args.Module)
	if module == "" {
		return nil, nil, fmt.Errorf("module must not be empty")
	}
	function := strings.TrimSpace(args.Function)

	if function == "" {
		return h.moduleDefinition(module)
	}

	// Direct definitions first: they tell us whether this is a defdelegate facade.
	direct, err := h.store.LookupFunction(module, function)
	if err != nil {
		return nil, nil, fmt.Errorf("looking up function: %w", err)
	}

	var b strings.Builder
	if len(direct) == 0 {
		// No direct definition. The function may still resolve through a
		// defdelegate chain recorded under a different arity/name form.
		resolved, err := h.store.LookupFollowDelegate(module, function)
		if err != nil {
			return nil, nil, fmt.Errorf("looking up function: %w", err)
		}
		if len(resolved) == 0 {
			return textResult(fmt.Sprintf("%s.%s is not in the index. It may be private to a use-chain (injected via __using__), dynamically generated by a macro, or misspelled. Try dexter_search or dexter_module_api %s.", module, function, module)), nil, nil
		}
		for _, r := range resolved {
			h.writeDefinition(&b, module, function, r)
		}
		return textResult(b.String()), nil, nil
	}

	for _, r := range direct {
		h.writeDefinition(&b, module, function, r)
		if r.Kind == "defdelegate" && r.DelegateTo != "" {
			targetFn := function
			if r.DelegateAs != "" {
				targetFn = r.DelegateAs
			}
			targets, err := h.store.LookupFollowDelegate(module, function)
			if err == nil && len(targets) > 0 {
				fmt.Fprintf(&b, "\nDelegates to %s.%s:\n", r.DelegateTo, targetFn)
				for _, t := range targets {
					h.writeDefinition(&b, r.DelegateTo, targetFn, t)
				}
			}
		}
	}
	return textResult(b.String()), nil, nil
}

func (h *Handler) moduleDefinition(module string) (*mcp.CallToolResult, any, error) {
	results, err := h.store.LookupModule(module)
	if err != nil {
		return nil, nil, fmt.Errorf("looking up module: %w", err)
	}
	if len(results) == 0 {
		return textResult(fmt.Sprintf("Module %s is not in the index. Use dexter_search to find the right name, or dexter_reindex if it was just created.", module)), nil, nil
	}

	var b strings.Builder
	for _, r := range results {
		fmt.Fprintf(&b, "%s %s - %s:%d\n", moduleKindLabel(r.Kind), module, h.relPath(r.FilePath), r.Line)
		if r.Kind != "defimpl" {
			if text, _, ok := h.lsp.ReadFileText(r.FilePath); ok {
				if doc := lsp.NewTokenizedFile(text).ExtractModuledoc(r.Line - 1); doc != "" {
					fmt.Fprintf(&b, "\n%s\n", strings.TrimRight(doc, "\n"))
				}
			}
		}
	}
	return textResult(b.String()), nil, nil
}

// writeDefinition renders one definition with location, @spec/@doc, and the
// definition head line.
func (h *Handler) writeDefinition(b *strings.Builder, module, function string, r store.LookupResult) {
	fmt.Fprintf(b, "%s (%s) - %s:%d\n", symbolName(module, function, r.Arity), r.Kind, h.relPath(r.FilePath), r.Line)

	text, _, ok := h.lsp.ReadFileText(r.FilePath)
	if !ok {
		return
	}
	tf := lsp.NewTokenizedFile(text)
	doc, spec := tf.ExtractDocAbove(r.Line - 1)
	if spec != "" {
		fmt.Fprintf(b, "%s\n", spec)
	}
	if head, ok := h.lsp.FileLine(r.FilePath, r.Line); ok {
		fmt.Fprintf(b, "%s\n", strings.TrimRight(head, " \t"))
	}
	if doc != "" {
		fmt.Fprintf(b, "\n%s\n", strings.TrimRight(doc, "\n"))
	}
}
